/* global d3, document */
(function() {
    "use strict";
    var fn = function() {

        var rects = d3.select("#table")
        //    .append("svg")
			.chart("Table")
			.name( 'taxon_oid' )
			.columns([ 'taxon_display_name', 'latitude', 'longitude', 'taxon_oid', 'ncbi_taxon_id' ])
        ;

        rects.draw( getJson() );

    };

    function getJson() {
        return [{
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Rod-shaped",
            "sequencing_gold_id": "Gp0012341",
            "ncbi_order": "Chroococcales",
            "latitude": "9.26583",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. KORDI-100 (genome sequencing)",
            "longitude": "158.40167",
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": "WARM",
            "study_gold_id": "Gs0033812",
            "ecosystem": "Environmental",
            "clade": "5.1-UC-A",
            "gold_id": "Gp0012341",
            "strain": "KORDI-100",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2507262013",
            "longhurst_description": "Trades - W. Pacific Warm Pool Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. KORDI-100",
            "domain": "Bacteria",
            "geo_location": "Pacific Ocean",
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "1280380",
            "analysis_project_id": "Ga0009892",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. KORDI-100",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Aerobe",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified",
            "depth_string": "0 m"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000430",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. CC9605",
            "longitude": null,
            "biotic_rel": "Free living",
            "depth": "51",
            "longhurst_code": "CCAL",
            "study_gold_id": "Gs0033799",
            "ecosystem": "Environmental",
            "clade": "5.1A-II",
            "gold_id": "Gp0000430",
            "strain": "CC9605",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": "Nonsporulating",
            "gram_stain": "Gram-",
            "taxon_oid": "637000310",
            "longhurst_description": "Coastal - California Upwelling Coastal Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. CC9605",
            "domain": "Bacteria",
            "geo_location": "California coast",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "110662",
            "analysis_project_id": "Ga0031133",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "sp.",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Rod-shaped",
            "sequencing_gold_id": "Gp0012340",
            "ncbi_order": "Chroococcales",
            "latitude": "32.00000",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. KORDI-52 (genome sequencing)",
            "longitude": "126.75000",
            "biotic_rel": null,
            "depth": "30",
            "longhurst_code": "KURO",
            "study_gold_id": "Gs0033812",
            "ecosystem": "Environmental",
            "clade": "5.1A-II",
            "gold_id": "Gp0012340",
            "strain": "KORDI-52",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2507262012",
            "longhurst_description": "Westerlies - Kuroshio Current Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. KORDI-52",
            "domain": "Bacteria",
            "geo_location": "East China Sea",
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "585425",
            "analysis_project_id": "Ga0009791",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. KORDI-52",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Aerobe",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0003233",
            "ncbi_order": "Chroococcales",
            "latitude": "39.64333",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH 8109",
            "longitude": "-70.46200",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NWCS",
            "study_gold_id": "Gs0033827",
            "ecosystem": "Environmental",
            "clade": "5.1A-II",
            "gold_id": "Gp0003233",
            "strain": "WH 8109",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2563366603",
            "longhurst_description": "Coastal - NW Atlantic Shelves Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 8109",
            "domain": "Bacteria",
            "geo_location": "Sargasso Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "166314",
            "analysis_project_id": "Ga0024209",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 8109",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000622",
            "ncbi_order": "Chroococcales",
            "latitude": "22.49500",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH8102",
            "longitude": "-65.60000",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NWCS",
            "study_gold_id": "Gs0033830",
            "ecosystem": "Environmental",
            "clade": "5.1A-III",
            "gold_id": "Gp0000622",
            "strain": "WH8102",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "637000314",
            "longhurst_description": "Coastal - NW Atlantic Shelves Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 8102",
            "domain": "Bacteria",
            "geo_location": "Tropical Atlantic ocean",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "84588",
            "analysis_project_id": "Ga0031145",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "sp.",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002097",
            "ncbi_order": "Chroococcales",
            "latitude": "41.66667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. BL107",
            "longitude": "2.80000",
            "biotic_rel": "Free living",
            "depth": "100",
            "longhurst_code": "MEDI",
            "study_gold_id": "Gs0033807",
            "ecosystem": "Environmental",
            "clade": "5.1A-IV",
            "gold_id": "Gp0002097",
            "strain": "BL107",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2623620351",
            "longhurst_description": "Westerlies - Mediterranean Sea, Black Sea Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. BL107",
            "domain": "Bacteria",
            "geo_location": "Blanes Bay in the Mediterranean Sea at a depth of 100m",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "313625",
            "analysis_project_id": "Ga0067679",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. BL107",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002097",
            "ncbi_order": "Chroococcales",
            "latitude": "41.66667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. BL107",
            "longitude": "2.80000",
            "biotic_rel": "Free living",
            "depth": "100",
            "longhurst_code": "MEDI",
            "study_gold_id": "Gs0033807",
            "ecosystem": "Environmental",
            "clade": "5.1A-IV",
            "gold_id": "Gp0002097",
            "strain": "BL107",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "639857006",
            "longhurst_description": "Westerlies - Mediterranean Sea, Black Sea Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. BL107",
            "domain": "Bacteria",
            "geo_location": "Blanes Bay in the Mediterranean Sea at a depth of 100m",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "313625",
            "analysis_project_id": "Ga0031129",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. BL107",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000432",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. CC9902",
            "longitude": null,
            "biotic_rel": "Free living",
            "depth": "5",
            "longhurst_code": "CCAL",
            "study_gold_id": "Gs0033799",
            "ecosystem": "Environmental",
            "clade": "5.1A-IV",
            "gold_id": "Gp0000432",
            "strain": "CC9902",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "637000311",
            "longhurst_description": "Coastal - California Upwelling Coastal Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. CC9902",
            "domain": "Bacteria",
            "geo_location": "California current",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "316279",
            "analysis_project_id": "Ga0031134",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "sp.",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Rod-shaped",
            "sequencing_gold_id": "Gp0012237",
            "ncbi_order": "Chroococcales",
            "latitude": "32.50000",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. KORDI-49 (genome sequencing)",
            "longitude": "126.00000",
            "biotic_rel": null,
            "depth": "20",
            "longhurst_code": "CHIN",
            "study_gold_id": "Gs0033812",
            "ecosystem": "Environmental",
            "clade": "5.1A-WPC1",
            "gold_id": "Gp0012237",
            "strain": "KORDI-49",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2507262011",
            "longhurst_description": "Coastal - China Sea Coastal Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. KORDI-49",
            "domain": "Bacteria",
            "geo_location": "East China Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "585423",
            "analysis_project_id": "Ga0009790",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. KORDI-49",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Aerobe",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0009723",
            "ncbi_order": "Chroococcales",
            "latitude": "41.52599",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH 8016",
            "longitude": "-70.67609",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NASW",
            "study_gold_id": "Gs0033803",
            "ecosystem": "Environmental",
            "clade": "5.1B-I",
            "gold_id": "Gp0009723",
            "strain": "WH 8016",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Nonmotile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2507262052",
            "longhurst_description": "Westerlies - N. Atlantic Subtropical Gyral Province (West) (STGW)",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 8016",
            "domain": "Bacteria",
            "geo_location": "Woods Hole, MA",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "166318",
            "analysis_project_id": "Ga0024874",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 8016",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Aerobe",
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002094",
            "ncbi_order": "Chroococcales",
            "latitude": "29.46667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. RS9916",
            "longitude": "34.91667",
            "biotic_rel": "Free living",
            "depth": "10",
            "longhurst_code": "REDS",
            "study_gold_id": "Gs0033823",
            "ecosystem": "Environmental",
            "clade": "5.1B-IX",
            "gold_id": "Gp0002094",
            "strain": "RS9916",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2623620281",
            "longhurst_description": "Coastal - Red Sea, Persian Gulf Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. RS9916",
            "domain": "Bacteria",
            "geo_location": "station A, Eilat, Red Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "221359",
            "analysis_project_id": "Ga0067678",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. RS9916",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002094",
            "ncbi_order": "Chroococcales",
            "latitude": "29.46667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. RS9916",
            "longitude": "34.91667",
            "biotic_rel": "Free living",
            "depth": "10",
            "longhurst_code": "REDS",
            "study_gold_id": "Gs0033823",
            "ecosystem": "Environmental",
            "clade": "5.1B-IX",
            "gold_id": "Gp0002094",
            "strain": "RS9916",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "639857007",
            "longhurst_description": "Coastal - Red Sea, Persian Gulf Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. RS9916",
            "domain": "Bacteria",
            "geo_location": "station A, Eilat, Red Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "221359",
            "analysis_project_id": "Ga0031140",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. RS9916",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000142",
            "ncbi_order": "Chroococcales",
            "latitude": "33.74230",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH7803",
            "longitude": "-67.49130",
            "biotic_rel": "Free living",
            "depth": "25",
            "longhurst_code": "NASW",
            "study_gold_id": "Gs0019915",
            "ecosystem": "Environmental",
            "clade": "5.1B-V",
            "gold_id": "Gp0000142",
            "strain": "WH 7803",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "640427149",
            "longhurst_description": "Westerlies - N. Atlantic Subtropical Gyral Province (West) (STGW)",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 7803",
            "domain": "Bacteria",
            "geo_location": "Sargasso Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "32051",
            "analysis_project_id": "Ga0031143",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 7803",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000142",
            "ncbi_order": "Chroococcales",
            "latitude": "33.74230",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH7803",
            "longitude": "-67.49130",
            "biotic_rel": "Free living",
            "depth": "25",
            "longhurst_code": "NASW",
            "study_gold_id": "Gs0019915",
            "ecosystem": "Environmental",
            "clade": "5.1B-V",
            "gold_id": "Gp0000142",
            "strain": "WH 7803",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2623620330",
            "longhurst_description": "Westerlies - N. Atlantic Subtropical Gyral Province (West) (STGW)",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 7803",
            "domain": "Bacteria",
            "geo_location": "Sargasso Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "32051",
            "analysis_project_id": "Ga0067152",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 7803",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002092",
            "ncbi_order": "Chroococcales",
            "latitude": "33.75000",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH7805",
            "longitude": "-67.50000",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NASW",
            "study_gold_id": "Gs0033829",
            "ecosystem": "Environmental",
            "clade": "5.1B-VI",
            "gold_id": "Gp0002092",
            "strain": "WH7805",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2623620868",
            "longhurst_description": "Westerlies - N. Atlantic Subtropical Gyral Province (West) (STGW)",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 7805",
            "domain": "Bacteria",
            "geo_location": "33N/67W",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "59931",
            "analysis_project_id": "Ga0076775",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 7805",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002092",
            "ncbi_order": "Chroococcales",
            "latitude": "33.75000",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH7805",
            "longitude": "-67.50000",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NASW",
            "study_gold_id": "Gs0033829",
            "ecosystem": "Environmental",
            "clade": "5.1B-VI",
            "gold_id": "Gp0002092",
            "strain": "WH7805",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "638341215",
            "longhurst_description": "Westerlies - N. Atlantic Subtropical Gyral Province (West) (STGW)",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 7805",
            "domain": "Bacteria",
            "geo_location": "33N/67W",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "59931",
            "analysis_project_id": "Ga0031144",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 7805",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0006220",
            "ncbi_order": "Chroococcales",
            "latitude": "29.46667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. RS9917",
            "longitude": "34.91667",
            "biotic_rel": "Free living",
            "depth": "10",
            "longhurst_code": "REDS",
            "study_gold_id": "Gs0033824",
            "ecosystem": "Environmental",
            "clade": "5.1B-VIII",
            "gold_id": "Gp0006220",
            "strain": "RS9917",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Marginal sea",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "638341213",
            "longhurst_description": "Coastal - Red Sea, Persian Gulf Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. RS9917",
            "domain": "Bacteria",
            "geo_location": "station A, Eilat, Red Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "221360",
            "analysis_project_id": "Ga0031141",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. RS9917",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0002093",
            "ncbi_order": "Chroococcales",
            "latitude": "41.05808",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. WH5701",
            "longitude": "-72.86560",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "NWCS",
            "study_gold_id": "Gs0033828",
            "ecosystem": "Environmental",
            "clade": "5.2",
            "gold_id": "Gp0002093",
            "strain": "WH5701",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "638341214",
            "longhurst_description": "Coastal - NW Atlantic Shelves Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. WH 5701",
            "domain": "Bacteria",
            "geo_location": "Long Island Sound",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "69042",
            "analysis_project_id": "Ga0031142",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. WH 5701",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": null,
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000143",
            "ncbi_order": "Chroococcales",
            "latitude": "39.16667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. RCC307",
            "longitude": "6.16667",
            "biotic_rel": "Free living",
            "depth": "15",
            "longhurst_code": "MEDI",
            "study_gold_id": "Gs0033821",
            "ecosystem": "Environmental",
            "clade": "5.3-I / X",
            "gold_id": "Gp0000143",
            "strain": "RCC 307",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "640427148",
            "longhurst_description": "Westerlies - Mediterranean Sea, Black Sea Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. RCC307",
            "domain": "Bacteria",
            "geo_location": "Seawater from the Mediterranean Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "316278",
            "analysis_project_id": "Ga0031139",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. RCC307",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": "Coccus-shaped",
            "sequencing_gold_id": "Gp0000143",
            "ncbi_order": "Chroococcales",
            "latitude": "39.16667",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. RCC307",
            "longitude": "6.16667",
            "biotic_rel": "Free living",
            "depth": "15",
            "longhurst_code": "MEDI",
            "study_gold_id": "Gs0033821",
            "ecosystem": "Environmental",
            "clade": "5.3-I / X",
            "gold_id": "Gp0000143",
            "strain": "RCC 307",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": "Motile",
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2623620283",
            "longhurst_description": "Westerlies - Mediterranean Sea, Black Sea Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. RCC307",
            "domain": "Bacteria",
            "geo_location": "Seawater from the Mediterranean Sea",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "316278",
            "analysis_project_id": "Ga0067153",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. RCC307",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Facultative",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0018820",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. CC9616",
            "longitude": null,
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": "CCAL",
            "study_gold_id": "Gs0033803",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0018820",
            "strain": "CC9616",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2517093019",
            "longhurst_description": "Coastal - California Upwelling Coastal Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. CC9616",
            "domain": "Bacteria",
            "geo_location": null,
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "110663",
            "analysis_project_id": "Ga0026647",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. CC9616",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0097362",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. NKBG 042902",
            "longitude": null,
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": null,
            "study_gold_id": "Gs0112237",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0097362",
            "strain": "NKBG 042902",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2585428034",
            "longhurst_description": null,
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. NKBG042902",
            "domain": "Bacteria",
            "geo_location": null,
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "490193",
            "analysis_project_id": "Ga0056671",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. NKBG042902",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0071509",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. NKBG15041c",
            "longitude": null,
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": null,
            "study_gold_id": "Gs0109685",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0071509",
            "strain": "NKBG15041c",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2579778681",
            "longhurst_description": null,
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. NKBG15041c",
            "domain": "Bacteria",
            "geo_location": null,
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "1407650",
            "analysis_project_id": "Ga0051930",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. NKBG15041c",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0009615",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. PCC 73109",
            "longitude": null,
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": null,
            "study_gold_id": "Gs0033818",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0009615",
            "strain": "PCC 73109",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2504643003",
            "longhurst_description": null,
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. PCC 73109",
            "domain": "Bacteria",
            "geo_location": null,
            "temp_range": null,
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "374982",
            "analysis_project_id": "Ga0010394",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. PCC 73109",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0005931",
            "ncbi_order": "Chroococcales",
            "latitude": "37.87100",
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. PCC 7336",
            "longitude": "-122.27200",
            "biotic_rel": "Free living",
            "depth": null,
            "longhurst_code": "CCAL",
            "study_gold_id": "Gs0014887",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0005931",
            "strain": "PCC 7336",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": "Gram-",
            "taxon_oid": "2506520048",
            "longhurst_description": "Coastal - California Upwelling Coastal Province",
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. PCC 7336",
            "domain": "Bacteria",
            "geo_location": "Berkeley, California, USA",
            "temp_range": "Mesophile",
            "specific_ecosystem": "Unclassified",
            "altitude": null,
            "ncbi_taxon_id": "195250",
            "analysis_project_id": "Ga0025409",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. PCC 7336",
            "ecosystem_category": "Aquatic",
            "oxygen_req": "Aerobe",
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }, {
            "combined_sample_flag": null,
            "genome_type": "isolate",
            "ecosystem_type": "Marine",
            "cell_shape": null,
            "sequencing_gold_id": "Gp0009763",
            "ncbi_order": "Chroococcales",
            "latitude": null,
            "ncbi_genus": "Synechococcus",
            "taxon_display_name": "Synechococcus sp. PCC 8807",
            "longitude": null,
            "biotic_rel": null,
            "depth": null,
            "longhurst_code": null,
            "study_gold_id": "Gs0033820",
            "ecosystem": "Environmental",
            "clade": null,
            "gold_id": "Gp0009763",
            "strain": "PCC 8807",
            "ncbi_family": null,
            "family": "unclassified",
            "ecosystem_subtype": "Pelagic",
            "motility": null,
            "sporulation": null,
            "gram_stain": null,
            "taxon_oid": "2504643002",
            "longhurst_description": null,
            "ncbi_class": null,
            "ncbi_species": "Synechococcus sp. PCC 8807",
            "domain": "Bacteria",
            "geo_location": null,
            "temp_range": null,
            "specific_ecosystem": null,
            "altitude": null,
            "ncbi_taxon_id": "195248",
            "analysis_project_id": "Ga0010202",
            "ncbi_phylum": "Cyanobacteria",
            "ir_order": "Chroococcales",
            "genus": "Synechococcus",
            "salinity": null,
            "species": "Synechococcus sp. PCC 8807",
            "ecosystem_category": "Aquatic",
            "oxygen_req": null,
            "ncbi_kingdom": "Bacteria",
            "ecotype": null,
            "phylum": "Cyanobacteria",
            "ir_class": "unclassified"
        }
        ];
    }
    if (document.readyState !== 'loading') {
        fn();
    } else if (document.addEventListener) {
        document.addEventListener('DOMContentLoaded', function() {
            fn();
        });
    } else {
        document.attachEvent('onreadystatechange', function() {
            if (document.readyState !== 'loading') {
                fn();
            }
        });
    }
}());
